# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
---
repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-toml
        exclude: "\\{\\{cookiecutter.package_name\\}\\}/.*"
      - id: check-yaml
        exclude: "\\{\\{cookiecutter.package_name\\}\\}/.*"

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.2
    hooks:
      - id: codespell
        exclude: poetry.lock

  - repo: https://github.com/motet-a/jinjalint
    rev: ''  # select a tag / sha to point at
    hooks:
      - id: jinjalint

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.29.0
    hooks:
      - id: yamllint
        exclude: "\\{\\{cookiecutter.package_name\\}\\}/.*"

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.33.0
    hooks:
      - id: markdownlint
        exclude: "\\{\\{cookiecutter.package_name\\}\\}/.*"

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]
        exclude: "\\{\\{cookiecutter.package_name\\}\\}/.*"

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        exclude: "\\{\\{cookiecutter.package_name\\}\\}/.*|hooks"

  - repo: https://github.com/PyCQA/prospector
    rev: v1.8.4
    hooks:
      - id: prospector
        args:
          - "-W"
          - "pyflakes"
          # avoid pylint_django
          - "--no-autodetect"
        exclude: "\\{\\{cookiecutter.package_name\\}\\}/.*|hooks"
  - repo: local
    hooks:
      - id: actionlint
        name: Lint GitHub Actions workflow files
        description: Runs actionlint to lint GitHub Actions workflow files
        types: ["yaml"]
        files: "^.github/workflows/"
        entry: actionlint
        language: golang
        additional_dependencies:
          - github.com/rhysd/actionlint/cmd/actionlint@latest

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.40.0
    hooks:
      - id: commitizen
        stages: [commit-msg]
