---
name: Test package
on:  # yamllint disable-line rule:truthy
  pull_request:
    paths:
      - '**.py'
      - 'pyproject.toml'
      - '!docs/**'
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.10, 3.11]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python {% raw %}${{ matrix.python-version }}{% endraw %}
        uses: actions/setup-python@v2
        with:
          python-version: {% raw %}${{ matrix.python-version }}{% endraw %}

      - name: Install tox
        run: pip install tox tox-gh-actions

      - name: Cache tox environments
        uses: actions/cache@v1
        with:
          path: .tox
          {% raw %}key: tox|${{ hashFiles('tox.ini')}}{% endraw %}

      - name: Test package
        run: tox

      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: {% raw %}${{ secrets.CODACY_PROJECT_TOKEN }}{% endraw %}
          coverage-reports: coverage.xml
