[tool.poetry]
name = "{{cookiecutter.package_name}}"
version = "{{cookiecutter.package_version}}"
license = "MIT"
description = "{{cookiecutter.project_description}}"
authors = ["{{cookiecutter.author_name}} <{{cookiecutter.author_email}}>"]
readme = "README.md"
repository = "{{ cookiecutter.repository }}"
documentation = "{{ cookiecutter.docs }}"

[tool.poetry.dependencies]
python = ">=3.8,<4.0"

[tool.poetry.group.dev.dependencies]
sphinx = "^6.1.3"
pre-commit = "^2.15.0"
pytest = "^7.2.1"
pytest-cov = "^3.0.0"
tox = "^3.24.4"
python-semantic-release = "^7.33.1"
black = "^23.1.0"
mypy = "^0.991"
pdoc = "^12.3.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.semantic_release]
version_variable = [
    "prototype_python_library/__init__.py:__version__",
    "pyproject.toml:version"
]
branch = "master"
upload_to_pypi = true
upload_to_release = true
build_command = "pip install poetry && poetry build"
