---
name: Apply cookiecutter to prototype project
on:  # yamllint disable-line rule:truthy
  push:
    branches: [master]
    paths:
      - .github/workflows/apply.yml
      - "*cookiecutter.package_name*/**"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install poetry
        run: pip install poetry

      - name: Install poetry environment
        run: poetry install

      - name: Run tests
        run: poetry run cookiecutter . --no-input

      - name: Lock poetry dependencies
        run: poetry --directory=template-pyproject lock

      - name: Pushes to prototype Python project repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.APPLY_TOKEN }}
        with:
          source-directory: template-pyproject/
          destination-github-username: '91nunocosta'
          destination-repository-name: 'template-pyproject'
          user-email: 91nunocosta@gmail.com
          target-branch: master
          commit-message: 'chore: apply ORIGIN_COMMIT'
