---
name: Test cookiecutter
on:  # yamllint disable-line rule:truthy
  push:
    branches: [master]
    paths:
      - "pyproject.toml"
      - pytest.py
      - "*cookiecutter.package_name*/**"
  pull_request:
    paths:
      - "pyproject.toml"
      - pytest.py
      - "*cookiecutter.package_name*/**"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install poetry
        run: pip install poetry

      - name: Install poetry environment
        run: poetry install

      - name: Run tests
        run: poetry run pytest
